---
name: Check dead links
on:
  pull_request:
  push:
    branches:
      - trying
      - staging
      - master
jobs:
  check-links:
    name: check validity of links
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: yarn install
    - run: yarn check-links
